bulidDjango/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from bulidDjango import views

urlpatterns = [
    path('demo/', include('demoApp.urls')),
    path('admin/', admin.site.urls),
    path('test/', views.test_page, name='test_page'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'bulidDjango.views.handler404'

demoApp/urls.py
from django.urls import path, re_path

from . import views

# describe the app name to avoid confusion with other apps in the project
# that may have the same name for their views and urls files
app_name = 'demoApp'
handler404 = 'demoApp.views.handler404'

urlpatterns = [
    path('', views.index, name='index'),
    path('test/', views.test_view, name='test_view'),
    path('test_form/', views.TestForm.as_view(), name='test_form'),
    path('test_model_form/', views.DemoModelFormView.as_view(), name='test_model_form'),
    path('display_date/', views.display_date, name='display_date'),
    path('testmethods/', views.MyView.as_view(), name='testmethods'),
    # path('getuser/<str:name>/<int:id>', views.pathview, name='pathview'),
    path('getuser/', views.query_view, name='qryview'),
    path('showform/', views.showform, name="showform"),
    path('getform/', views.getform, name="redirect_get_form_data"),
    path('getdish/<str:dish_name>', views.custom_path_view, name='custompath'),
    path('permanent_redirect/', views.make_user_permanent_redirect, name='permanent_redirect'),
    path('products/', views.ProductListView.as_view(), name='product_detail'),
    # regex
    re_path(r'^getuser/(?P<name>[a-z]+)/(?P<id>[0-9]{1,2})/$', views.pathview, name='pathview'),
    re_path(r'^use_regex/getuser/([0-9]{1,2})/$', views.pathview2, name='pathview'),
    path('langs/', views.showing_data, name='langs'),

    # url(r'^users_only/', login_required(myview)),
    #
    # url(r'^category/', permission_required('myapp.change_category', login_url='login')(myview)),

]

templates/_header.html
<footer style="background-color: #EE9927">
<nav>
    <ul>
        <li style="display: inline-block ; width: 120px;">Home</li>
        <li style="display: inline-block ; width: 120px;">About</li>
        <li style="display: inline-block ; width: 120px;">Menu</li>
        <li style="display: inline-block ; width: 120px;">Contact</li>
    </ul>
</nav>
</footer>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include '_header.html' %}
<main>
    {% block content %}
    {% endblock %}
</main>
</body>
</html>

templates/dish.html
{% extends 'base.html' %}
{% comment "This is a comment" %}
{% endcomment %}
{% block content %}
My fav is: {{ dish_name|upper }}
{% endblock content %}

templates/form.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'demoApp:redirect_get_form_data' %}" method="POST">
    {% csrf_token %}
    <p>Name :<input type="text" name="name"></p>
    <p>UserID: <input type="number" name="id"></p>
    <input type="submit">
</form>
{% endblock content %}

templates/form2.html
{% extends 'base.html' %}
{% block content %}
<div>
    <form action="{% url 'demoApp:test_form' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
</form>
</div>
{% endblock content %}

templates/form3.html
{% extends 'base.html' %}
{% block content %}
<div>
    <form action="{% url 'demoApp:test_model_form' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
</form>
</div>
{% endblock content %}

templates/langs.html
{% extends 'base.html' %}
{% block content %}
{% comment %}
Add another template
{% endcomment %}
{% include 'product.html' %}

    <h1>Langs</h1>

    {% for lang in langs %}
        <p>{{ lang }}</p>
    {% endfor %}

    <ul>
        {% for lang in langs %}
        <li>{{ forloop.counter }} : {{ lang }}</li>
        {% endfor %}
    </ul>

    <ul>
        {% for lang in langs %}
        <li>{{ forloop.revcounter }} : {{ lang }}</li>
        {% endfor %}

    </ul>

    <ul>
        {% for lang in langs %}
        {% comment  %}
            forloop.first: True if this is the first time through the loop
        {% endcomment %}
        <li>{{ forloop.first }} : {{ lang }}</li>

        {% comment  %}
            forloop.last: True if this is the last time through the loop
        {% endcomment %}
        <li>{{ forloop.last }} : {{ lang }}</li>
        {% endfor %}
    </ul>

    {% for key,value in dict_example.items %}
        <p>{{ key }} - {{ value }}</p>
    {% endfor %}

    <h1>Nested loops</h1>
    {% for key, values in dct.items %}
        <p>{{ forloop.counter }}:{{ key }}</p>
        <ul>
            {% for value in values %}
            <li> {{ value }}</li>
            {% endfor %}
        </ul>
    {% endfor %}

{% with rate=5 %}
    {% for number in numbers %}
        Interest = {{ number|floatformat:2 }} * {{ rate }}
    {% endfor %}
{% endwith %}

    <p>{{ value|default:"nothing" }}</p>
    <p>{{ word|first }}</p>
    <p>{{ word|length }}</p>
    <p>{{ word|length_is:"5" }}</p>
    <p>{{ word|join:" _ " }} </p>
    <p>{{ word|title }}</p>
    <p>{{ word|wordcount }}</p>
{% endblock content %}

templates/product.html
{% if user.is_authenticated %}
    {#  to be rendeed if the user has been authenticated  #}
    <p>Hello {{ user }}</p>
{% else %}
    <p>You are not authenticated</p>
{% endif %}

{% if perms.myapp.change_category %}
  {#  To be rendered for users having required permission #}
{% endif %}

templates/showData.html
{% extends 'base.html' %}
{% block content %}
<p>name is: {{ name }} and id is: {{ id }}</p>
{% endblock content %}

templates/show_data.html
{% extends 'base.html' %}
{% block content %}
<p>"Done, the data has been sent, form is valid"</p>
<p>your name is: {{ name }} </p>
<p>your email is: {{ email }}</p>
<p>your address is: {{ address }}</p>
{% endblock content %}